CREATE TABLE `menu` (
	`Key`	BIGINT	NOT NULL	DEFAULT AUTO_INCREMENT,
	`store_id`	BIGINT	NOT NULL	DEFAULT AUTO_INCREMENT,
	`menu_name`	VARCHAR(255)	NOT NULL,
	`price`	BIGINT	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`updated_at`	DATETIME	NOT NULL,
	`deleted_at`	DATETIME	NULL	DEFAULT Default : NULL
);

CREATE TABLE `review` (
	`Key`	BIGINT	NOT NULL	DEFAULT AUTO_INCREMENT,
	`user_id`	BIGINT	NOT NULL,
	`content`	VARCHAR(600)	NOT NULL,
	`rating`	BIGINT	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`order_id`	BIGINT	NOT NULL,
	`store_id`	BIGINT	NOT NULL
);

CREATE TABLE `user` (
	`id`	VARCHAR(255)	NOT NULL,
	`name`	VARCHAR(100)	NOT NULL,
	`Field`	VARCHAR(100)	NOT NULL,
	`password`	VARCHAR(100)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`updated_at`	DATETIME	NOT NULL,
	`role`	VARCHAR(255)	NOT NULL	DEFAULT ENUM,
	`address`	VARCHAR(300)	NOT NULL
);

CREATE TABLE `store` (
	`id`	BIGINT	NOT NULL	DEFAULT AUTO_INCREMENT,
	`owner_id`	BIGINT	NOT NULL,
	`store_name`	VARCHAR(100)	NOT NULL,
	`order_min`	INT	NOT NULL	DEFAULT 0,
	`about`	VARVHAR(300)	NOT NULL,
	`opened_at`	DATETIME	NOT NULL,
	`closed_at`	DATETIME	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`deleted_at`	DATETIME	NULL	DEFAULT Default : NULL
);

CREATE TABLE `orders` (
	`id`	BIGINT	NOT NULL	DEFAULT AUTO_INCREMET,
	`menu_id`	BIGINT	NOT NULL,
	`store_id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`order_state`	VARCHAR(50)	NOT NULL	DEFAULT ENUM,
	`created_at`	DATETIME	NOT NULL
);

ALTER TABLE `menu` ADD CONSTRAINT `PK_MENU` PRIMARY KEY (
	`Key`
);

ALTER TABLE `review` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`Key`
);

ALTER TABLE `user` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`id`
);

ALTER TABLE `store` ADD CONSTRAINT `PK_STORE` PRIMARY KEY (
	`id`
);

ALTER TABLE `orders` ADD CONSTRAINT `PK_ORDERS` PRIMARY KEY (
	`id`
);

